### PR TITLE
Auto initialize in `startproc`

### LINKED ISSUE #70: Reusing a compressor
This was found here: https://github.com/JuliaIO/JLD2.jl/issues/599

When using a `ZstdFrameCompressor` or a `ZstdCompressor`, you reproducably get a segfault when trying to reuse the same compressor instance:

I don't know if this can be made to *just work*, but I hope that this can at least be caught in time and throw an error instead.

```
using CodecZstd, TranscodingStreams

compressor = ZstdFrameCompressor()
x = rand(UInt8, 4*10^7);
TranscodingStreams.initialize(compressor)
ret1 = transcode(compressor, x);
TranscodingStreams.finalize(compressor)

# compress again using the same compressor
TranscodingStreams.initialize(compressor) # segfault happens here!
# ret2 = transcode(compressor, x);
# TranscodingStreams.finalize(compressor)
```

```
[1706176] signal (11.1): Segmentation fault
in expression starting at REPL[7]:1
ZSTD_CCtx_reset at /home/jisensee/.julia/artifacts/4c45bf9c8292490acd9463bbfbf168277d9720b6/lib/libzstd.so (unknown line)
ZSTD_initCStream at /home/jisensee/.julia/artifacts/4c45bf9c8292490acd9463bbfbf168277d9720b6/lib/libzstd.so (unknown line)
ZSTD_initCStream at /home/jisensee/.julia/packages/CodecZstd/KmRP9/src/LibZstd_clang.jl:277 [inlined]
initialize! at /home/jisensee/.julia/packages/CodecZstd/KmRP9/src/libzstd.jl:60 [inlined]
initialize at /home/jisensee/.julia/packages/CodecZstd/KmRP9/src/compression.jl:82
```

### PR DESCRIPTION
**Pull request by nhz2**
Fixes #70.  Third time's the charm

This PR avoids the complexity of interacting with GC in #71 by checking if the context is null when `startproc` is called.
If the context is null `startproc` initializes the context.

This means `finalize` is still needed to prevent memory leaks, but there is no issue of use after free.

### CODE REVIEW

File: src/compression.jl [hunk 1]
```diff
@@ -111,6 +111,9 @@ function TranscodingStreams.startproc(codec::ZstdCompressor, mode::Symbol, error
 end
 
 function TranscodingStreams.process(codec::ZstdCompressor, input::Memory, output::Memory, error::Error)
+    if codec.cstream.ptr == C_NULL
+        error("startproc must be called before process")
```
Comment (nhz2) [inline src/compression.jl:115]: This error should also be unreachable in normal operation.

File: src/compression.jl [hunk 2]
```diff
@@ -96,12 +86,22 @@ function TranscodingStreams.finalize(codec::ZstdCompressor)
...
 function TranscodingStreams.startproc(codec::ZstdCompressor, mode::Symbol, error::Error)
+    if codec.cstream.ptr == C_NULL
+        ptr = LibZstd.ZSTD_createCStream()
+        if ptr == C_NULL
+            throw(OutOfMemoryError())
+        end
+        codec.cstream.ptr = ptr
+        i_code = initialize!(codec.cstream, codec.level)
+        if iserror(i_code)
+            error[] = ErrorException("zstd initialization error")
```
Comment (nhz2) [inline src/compression.jl:101]: These errors are unreachable unless there is some allocation error.

File: src/compression.jl [hunk 3]
```diff
@@ -78,16 +78,6 @@ end
 # Methods
 # -------
 
-function TranscodingStreams.initialize(codec::ZstdCompressor)
-    code = initialize!(codec.cstream, codec.level)
-    if iserror(code)
-        zstderror(codec.cstream, code)
-    end
-    reset!(codec.cstream.ibuffer)
-    reset!(codec.cstream.obuffer)
```
Comment (mkitti) [inline src/compression.jl:87]: Where does this happen now?

File: src/compression.jl [hunk 4]
```diff
@@ -96,12 +86,22 @@ function TranscodingStreams.finalize(codec::ZstdCompressor)
...
+    nothing
 end
 
 function TranscodingStreams.startproc(codec::ZstdCompressor, mode::Symbol, error::Error)
+    if codec.cstream.ptr == C_NULL
+        ptr = LibZstd.ZSTD_createCStream()
+        if ptr == C_NULL
+            throw(OutOfMemoryError())
+        end
+        codec.cstream.ptr = ptr
```
Comment (mkitti) [inline src/compression.jl:98]:
```suggestion
        codec.cstream.ptr = LibZstd.ZSTD_createCStream()
        if codec.cstream.ptr == C_NULL
            throw(OutOfMemoryError())
        end
```

There is no point in using a temporary variable here. `codec.cstream.ptr` starts as `C_NULL` anyways.

File: src/decompression.jl [hunk 5]
```diff
@@ -51,12 +41,22 @@ function TranscodingStreams.finalize(codec::ZstdDecompressor)
...
+    nothing
 end
 
 function TranscodingStreams.startproc(codec::ZstdDecompressor, mode::Symbol, error::Error)
+    if codec.dstream.ptr == C_NULL
+        ptr = LibZstd.ZSTD_createDStream()
+        if ptr == C_NULL
+            throw(OutOfMemoryError())
+        end
+        codec.dstream.ptr = ptr
```
Comment (mkitti) [inline src/decompression.jl:53]:
```suggestion
        codec.dstream.ptr = LibZstd.ZSTD_createDStream()
        if codec.dstream.ptr == C_NULL
            throw(OutOfMemoryError())
        end
```

File: src/compression.jl [hunk 6]
```diff
@@ -96,12 +86,22 @@ function TranscodingStreams.finalize(codec::ZstdCompressor)
...
+        i_code = initialize!(codec.cstream, codec.level)
```
Comment (mkitti) [inline src/compression.jl:99]: Also see notes in #73

Should `initialize!` throw so we can catch it here and transmit the error?

**Review by mkitti — CHANGES_REQUESTED** [review]
Interesting approach. We may still want to consider the finalizer.

File: test/runtests.jl [hunk 7]
```diff
@@ -158,4 +158,72 @@ include("utils.jl")
...
+            codec = Codec()
+            TranscodingStreams.initialize(codec)
+            TranscodingStreams.finalize(codec)
+            data = [0x00,0x01]
+            GC.@preserve data let m = TranscodingStreams.Memory(pointer(data), length(data))
+                try
+                    TranscodingStreams.expectedsize(codec, m)
+                catch
+                end
+                try
```
[the remark this answers is not in the document]
Comment (nhz2) [reply test/runtests.jl:202]: I have this in the title of the testset, so this is redundant. Later we can move this test to `TestsForCodecPackages.jl` and add more details then.

File: src/compression.jl (hunk 3 above)
Comment (nhz2) [reply src/compression.jl:87]: This happens in `reset!`
https://github.com/JuliaIO/CodecZstd.jl/blob/60079dd3d5d7da7e32cd75f8361c6584fb36fe24/src/libzstd.jl#L73-L74

Which is called in `startproc` https://github.com/JuliaIO/CodecZstd.jl/blob/60079dd3d5d7da7e32cd75f8361c6584fb36fe24/src/compression.jl#L104

**Comment by nhz2** [comment]
> Interesting approach. We may still want to consider the finalizer.

Yes, having a finalizer should be compatible with this PR, and would also prevent memory leaks.

File: src/compression.jl (hunk 2 above)
Comment (nhz2) [reply src/compression.jl:100]: I'm not sure if even that would reliably trigger an error specifically here, because memory allocations are happening in `ZSTD_createCStream`.

**Comment by nhz2** [comment]
@mkitti Could you review this PR again, I think I addressed your comments.

**Comment by mkitti** [comment]
Overall, it looks fine. I will try to look more closely tonight.

**Review by mkitti — APPROVED** [review]

**Comment by ali-ramadhan** [comment]
Thank you @nhz2 and @mkitti! This fixes https://github.com/JuliaIO/JLD2.jl/issues/599 which will allow us to use zstd to compress Oceananigans.jl outputs.

Would it be possible to tag a new version of CodecZstd.jl?
